# Configuration for this blog
# it is written in Toml

[blog]
# What is your blog's name?
name = "BlogName"
# What is your blog about?
description = "BlogDescription" 
# your blog's url(ends without '/'), if you don't have one,  leave here blank
url = "http://your-blog.org"
# where are the templates?
templates = "classic"

[author]
name = "me"  # better be your github's username
email = "me@some.com"  # your email address
